name = "progu-mc"
author = "dots"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6d66abe61cda00606b869080b6f12e34756de0bb4a4225b38231349ecd37bf8"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
